# Generated by Django 3.1.2 on 2020-10-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('in_stock', models.BooleanField(default=False)),
                ('link', models.TextField()),
                ('store_name', models.CharField(max_length=30)),
            ],
        ),
    ]
